version: '3'

volumes:
  data_volume: {}
  media_volume: {}
  static_volume: {}

services:

  redis:
    image: redis
    restart: unless-stopped

  database:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - 'data_volume:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=123'

  webapp:
    build:
      context: ..
      dockerfile: docker/webapp/Dockerfile
    restart: unless-stopped
    command: /bin/sh /app/docker/start.sh
    entrypoint: /app/docker/entrypoint.sh
    env_file:
      - webapp/.env
    volumes:
      - 'static_volume:/app/source/assets/static/'
      - 'media_volume:/app/source/media/'
    depends_on:
      - database
    expose:
      - 8000

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - 'static_volume:/app/static-files/'
      - 'media_volume:/app/media-files/'
    depends_on:
      - webapp
    ports:
      - 8000:80
